/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const doc = (id, label) => ({ type: "doc", id: `ske/${id}`, label });
const category = (label, items, slug) => ({
  type: "category", label, items,
  link: { type: "generated-index", slug },
});
const portalDoc = (id, label) => doc(`integrations/portal-controller/${id}`, label);

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

  mainSidebar: [{ type: "autogenerated", dirName: "main" }],
  workshopSidebar: [{ type: "autogenerated", dirName: "workshop" }],
  skeSidebar: [
    doc("intro", "Overview"),
    category("Install SKE", [
      doc("installing-ske/intro", "Requirements and access tokens"),
      doc("installing-ske/install-with-operator", "Install SKE with the Operator"),
      doc("installing-ske/air-gapped", "Air-gapped installation"),
      doc("installing-ske/migrating-from-kratix", "Migrate from open-source Kratix"),
    ], "/category/enterprise-install-ske"),
    category("Build and evolve Promises", [
      doc("guides/promise-development", "Build and test a database Promise"),
      doc("promise-testing-framework/intro", "Test Promise pipelines"),
      doc("guides/promise-from-tf-module", "Create a Promise from a Terraform module"),
      doc("guides/scheduling-terraform-workspaces", "Schedule resources to Terraform workspaces"),
      doc("guides/promise-upgrades", "Roll out Promise upgrades"),
      doc("integrations/skelift", "SKE Lift (Preview)"),
    ], "/category/build-and-evolve-promises"),
    category("Operate your platform", [
      doc("reference/parts-of-a-platform", "Platform architecture"),
      doc("operations/production-readiness", "Prepare SKE for production"),
      doc("installing-ske/upgrades", "Upgrade SKE"),
      doc("installing-ske/backup-and-restore", "Backup and restore"),
      category("Health checks", [
        doc("installing-ske/ske-health-agent", "Install and configure the Health Agent"),
        doc("guides/healthchecks", "Add health checks to a Promise"),
        doc("guides/healthchecks-nonk8s", "Check non-Kubernetes resources"),
        doc("guides/health-records-from-a-bucket", "Migrate health records to a bucket"),
      ], "/category/enterprise-health-checks"),
      category("SKE GUI", [doc("installing-ske/ske-gui", "Install the GUI"), doc("guides/ske-gui", "Use the GUI")], "/category/enterprise-ske-gui"),
      doc("operations/troubleshooting", "Troubleshoot SKE"),
    ], "/category/enterprise-operate-your-platform"),
    category("Portal integrations", [
      doc("integrations/portal-integrations", "Overview"),
      category("Backstage", [
        portalDoc("backstage/intro", "Overview"),
        portalDoc("backstage/generate-entities", "Generate Backstage entities"),
        portalDoc("backstage/configure-backstage", "Configure Backstage"),
        portalDoc("backstage/send-resource-requests", "Send resource requests to Kratix"),
        portalDoc("backstage/customising-the-request-template", "Customise entities and request templates"),
        portalDoc("backstage/frontend-plugin-reference", "Frontend plugin API"),
        portalDoc("backstage/backend-plugin-reference", "Backend plugin API"),
        portalDoc("backstage/migrating-from-backstage", "Migrate from the Backstage Controller"),
      ], "/category/enterprise-backstage"),
      category("Cortex", [
        portalDoc("cortex/intro", "Overview"),
        portalDoc("cortex/generate-entities", "Generate Cortex entities and workflows"),
        portalDoc("cortex/send-resource-requests", "Send resource requests to Kratix"),
        portalDoc("cortex/examples", "Customise entities and workflows"),
        portalDoc("cortex/migrating-from-cortex", "Migrate from the Cortex Controller"),
      ], "/category/enterprise-cortex"),
      doc("integrations/port", "Port (Preview)"),
      category("Portal Controller", [
        portalDoc("intro", "How it works"),
        portalDoc("installation", "Install and upgrade"),
        portalDoc("customization/job-customization", "Configure sync and setup Jobs"),
        portalDoc("troubleshooting", "Troubleshoot portal sync"),
        category("Reference", [
          portalDoc("reference/portal-configuration", "Portal configuration and bindings"),
          portalDoc("customization/intro", "PortalCustomization"),
          portalDoc("customization/recipe-reference", "Portal Patch recipes"),
          portalDoc("reference/adapter", "Adapter reference"),
        ], "/category/enterprise-portal-controller-reference"),
      ], "/category/enterprise-portal-controller"),
      category("Deprecated controllers", [
        category("Backstage Controller", [
          doc("integrations/backstage/intro", "Overview"),
          doc("integrations/backstage/installation/intro", "Install the Backstage integration"),
          doc("integrations/backstage/installation/entity-state-store", "Create the entity state store"),
          doc("integrations/backstage/installation/backstage", "Configure catalogue ingestion"),
          doc("integrations/backstage/installation/generating-backstage-components", "Generate Backstage Components"),
          doc("integrations/backstage/air-gapped-installation/intro", "Air-gapped installation"),
        ], "/category/enterprise-backstage-controller"),
        category("Backstage generator", [
          doc("integrations/backstage/reference/index", "Overview"),
          doc("integrations/backstage/reference/generator", "SKE Backstage Generator"),
          doc("integrations/backstage/reference/generator-promise", "SKE Component Promise"),
        ], "/category/enterprise-backstage-generator"),
        category("Cortex Controller", [
          doc("integrations/cortex/intro", "Overview"),
          doc("integrations/cortex/installation", "Configure Cortex"),
          doc("integrations/cortex/generating-cortex-components", "Use the Cortex integration"),
        ], "/category/enterprise-cortex-controller"),
      ], "/category/enterprise-deprecated-controllers"),
    ], "/category/enterprise-portal-integrations"),
    category("Tool integrations", [doc("integrations/tfe", "Terraform Enterprise and HCP Terraform"), doc("integrations/mcp", "MCP Server (Preview)")], "/category/enterprise-tool-integrations"),
    category("Reference", [
      doc("reference/index", "API and CLI index"),
      doc("reference/ske-operator", "SKE Operator API"),
      doc("reference/healthdefinition", "HealthDefinition"),
      doc("reference/healthsource", "HealthSource"),
      doc("reference/promise-upgrades/upgrade-plans", "UpgradePlan"),
      doc("reference/promise-upgrades/upgrade-runs", "UpgradeRun"),
      category("Promise Testing CLI", [
        doc("promise-testing-framework/reference/kratix-test", "kratix test"),
        doc("promise-testing-framework/reference/kratix-test-pipeline", "kratix test pipeline"),
        doc("promise-testing-framework/reference/kratix-test-stage", "kratix test stage"),
      ], "/category/command-reference-1"),
    ], "/category/enterprise-reference"),
    category("Releases and support", [
      doc("releases/index", "Release index"),
      doc("releases/compatibility", "Supported versions and compatibility"),
      doc("releases/ske", "SKE"),
      category("Platform components", [
        doc("releases/platform/ske-operator", "SKE Operator"),
        doc("releases/platform/ske-health-agent", "SKE Health Agent"),
        doc("releases/platform/ske-gui", "SKE GUI"),
        doc("releases/platform/promise-testing-framework", "Promise Testing Framework"),
      ], "/category/platform"),
      category("Integrations", [
        doc("releases/integrations/ske-portal-controller", "Portal Controller"),
        doc("releases/integrations/portal-patch", "Portal Patch"),
        doc("releases/integrations/backstage", "Backstage plugins"),
        doc("releases/integrations/ske-port-controller", "Port Controller"),
        doc("releases/integrations/ske-mcp-server", "MCP Server"),
      ], "/category/integrations"),
      category("Pipeline stages", [doc("releases/pipeline-stages/tfstate-finder", "Terraform State Finder")], "/category/pipeline-stages"),
      category("Deprecated components", [
        doc("releases/deprecated/backstage-controller", "Backstage Controller"),
        doc("releases/deprecated/backstage-generator", "Backstage Generator"),
        doc("releases/deprecated/cortex-controller", "Cortex Controller"),
      ], "/category/deprecated"),
      doc("support", "Support policy"),
    ], "/category/enterprise-releases-and-support"),
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
