// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  mainSidebar: [{ type: "autogenerated", dirName: "main" }],
  workshopSidebar: [{ type: "autogenerated", dirName: "workshop" }],
  skeSidebar: [{ type: "autogenerated", dirName: "ske" }],
};
