const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..');
const plugin = path.join(root, 'node_modules/@docusaurus/plugin-content-docs/lib');
const { DefaultSidebarItemsGenerator } = require(path.join(plugin, 'sidebars/generator'));
const { isCategoryIndex } = require(path.join(plugin, 'docs'));
const { DEFAULT_OPTIONS } = require(path.join(plugin, 'options'));

// Build metadata exercises Docusaurus's actual parser rather than duplicating it.
const metadataDir = path.join(root, '.docusaurus/docusaurus-plugin-content-docs/default');
const docs = fs.readdirSync(metadataDir)
  .filter(file => file.startsWith('site-docs-') && file.endsWith('.json'))
  .map(file => JSON.parse(fs.readFileSync(path.join(metadataDir, file), 'utf8')))
  .filter(doc => fs.existsSync(path.join(root, doc.source.replace('@site/', ''))));
const categoriesMetadata = {};
function readCategories(directory) {
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const file = path.join(directory, entry.name);
    if (entry.isDirectory()) readCategories(file);
    else if (entry.name === '_category_.json') {
      categoriesMetadata[path.relative(path.join(root, 'docs'), directory)] = JSON.parse(fs.readFileSync(file, 'utf8'));
    }
  }
}
readCategories(path.join(root, 'docs/ske'));
const generate = documents => DefaultSidebarItemsGenerator({
  docs: documents,
  item: { type: 'autogenerated', dirName: 'ske' },
  categoriesMetadata,
  numberPrefixParser: DEFAULT_OPTIONS.numberPrefixParser,
  isCategoryIndex,
});
const walk = items => items.flatMap(item => item.type === 'category' ? [item, ...walk(item.items)] : [item]);

test('Enterprise discovers pages from its folder structure', () => {
  assert.deepEqual(require('../sidebars').skeSidebar, [
    { type: 'autogenerated', dirName: 'ske' },
  ]);
});

test('Every Enterprise folder has a unique card landing page', () => {
  const categories = walk(generate(docs)).filter(item => item.type === 'category');
  assert.ok(categories.length > 0, 'Run yarn build before these tests');
  for (const category of categories) {
    assert.equal(category.link?.type, 'generated-index', category.label);
    assert.ok(category.link.slug.startsWith('/category/'), category.label);
  }
  assert.equal(new Set(categories.map(item => item.link.slug)).size, categories.length);
});

test('Every navigable Enterprise document is discovered once', () => {
  const discovered = walk(generate(docs)).filter(item => item.type === 'doc').map(item => item.id);
  const expected = docs.filter(doc => doc.sourceDirName === 'ske' || doc.sourceDirName.startsWith('ske/')).map(doc => doc.id);
  assert.deepEqual([...discovered].sort(), [...expected].sort());
  assert.equal(new Set(discovered).size, discovered.length);
  for (const doc of docs.filter(doc => expected.includes(doc.id))) {
    assert.ok(doc.permalink.startsWith('/ske/'), doc.id);
  }
});

test('Adding a document requires no manual sidebar registration', () => {
  const exemplar = docs.find(doc => doc.sourceDirName.startsWith('ske/'));
  assert.ok(exemplar, 'Run yarn build before these tests');
  const added = {
    ...exemplar,
    id: `${exemplar.sourceDirName}/new-page`,
    source: `${exemplar.source.slice(0, exemplar.source.lastIndexOf('/'))}/new-page.mdx`,
    title: 'New page',
    frontMatter: { sidebar_label: 'New page' },
    sidebarPosition: 999,
  };
  assert.ok(walk(generate([...docs, added])).some(item => item.id === added.id));
});

test('Linked supporting pages retain Enterprise navigation without extra sidebar entries', () => {
  const supporting = docs.filter(doc => doc.sourceDirName.startsWith('ske-supporting/'));
  assert.ok(supporting.length > 0);
  const discovered = walk(generate(docs)).filter(item => item.type === 'doc').map(item => item.id);
  for (const doc of supporting) {
    assert.equal(doc.frontMatter.displayed_sidebar, 'skeSidebar', doc.id);
    assert.ok(doc.permalink.startsWith('/ske/'), doc.id);
    assert.ok(!discovered.includes(doc.id), doc.id);
  }
});
