const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const sidebars = require('../sidebars');

// Labels and hierarchy are the approved reader journeys, independent of filenames.
const expected = [
  'Overview',
  ['Install SKE', 'Requirements and access tokens', 'Install SKE with the Operator', 'Air-gapped installation', 'Migrate from open-source Kratix'],
  ['Build and evolve Promises', 'Build and test a database Promise', 'Test Promise pipelines', 'Create a Promise from a Terraform module', 'Schedule resources to Terraform workspaces', 'Roll out Promise upgrades', 'SKE Lift (Preview)'],
  ['Operate your platform', 'Platform architecture', 'Prepare SKE for production', 'Upgrade SKE', 'Backup and restore', ['Health checks', 'Install and configure the Health Agent', 'Add health checks to a Promise', 'Check non-Kubernetes resources', 'Migrate health records to a bucket'], ['SKE GUI', 'Install the GUI', 'Use the GUI'], 'Troubleshoot SKE'],
  ['Portal integrations', 'Overview', ['Backstage', 'Overview', 'Generate Backstage entities', 'Configure Backstage', 'Send resource requests to Kratix', 'Customise entities and request templates', 'Frontend plugin API', 'Backend plugin API', 'Migrate from the Backstage Controller'], ['Cortex', 'Overview', 'Generate Cortex entities and workflows', 'Send resource requests to Kratix', 'Customise entities and workflows', 'Migrate from the Cortex Controller'], 'Port (Preview)', ['Portal Controller', 'How it works', 'Install and upgrade', 'Configure sync and setup Jobs', 'Troubleshoot portal sync', ['Reference', 'Portal configuration and bindings', 'PortalCustomization', 'Portal Patch recipes', 'Adapter reference']], ['Deprecated controllers', ['Backstage Controller', 'Overview', 'Install the Backstage integration', 'Create the entity state store', 'Configure catalogue ingestion', 'Generate Backstage Components', 'Air-gapped installation'], ['Backstage generator', 'Overview', 'SKE Backstage Generator', 'SKE Component Promise'], ['Cortex Controller', 'Overview', 'Configure Cortex', 'Use the Cortex integration']]],
  ['Tool integrations', 'Terraform Enterprise and HCP Terraform', 'MCP Server (Preview)'],
  ['Reference', 'API and CLI index', 'SKE Operator API', 'HealthDefinition', 'HealthSource', 'UpgradePlan', 'UpgradeRun', ['Promise Testing CLI', 'kratix test', 'kratix test pipeline', 'kratix test stage']],
  ['Releases and support', 'Release index', 'Supported versions and compatibility', 'SKE', ['Platform components', 'SKE Operator', 'SKE Health Agent', 'SKE GUI', 'Promise Testing Framework'], ['Integrations', 'Portal Controller', 'Portal Patch', 'Backstage plugins', 'Port Controller', 'MCP Server'], ['Pipeline stages', 'Terraform State Finder'], ['Deprecated components', 'Backstage Controller', 'Backstage Generator', 'Cortex Controller'], 'Support policy'],
];
const shape = items => items.map(item => item.type === 'category' ? [item.label, ...shape(item.items)] : item.label);
const leaves = items => items.flatMap(item => item.type === 'category' ? [...(item.link?.type === 'doc' ? [item.link.id] : []), ...leaves(item.items)] : [typeof item === 'string' ? item : item.id]);
const groups = items => items.flatMap(item => item.type === 'category' ? [item, ...groups(item.items)] : []);
const ids = leaves(sidebars.skeSidebar);

test('Each approved leaf resolves to its canonical document in journey order', () => {
  assert.deepEqual(ids, require('./fixtures/enterprise-sidebar-ids.json'));
});

test('Enterprise follows the complete approved tree and order', () => assert.deepEqual(shape(sidebars.skeSidebar), expected));
test('Main and Workshop retain filesystem navigation', () => {
  assert.deepEqual(sidebars.mainSidebar, [{type: 'autogenerated', dirName: 'main'}]);
  assert.deepEqual(sidebars.workshopSidebar, [{type: 'autogenerated', dirName: 'workshop'}]);
});
test('Every canonical document has one sidebar owner', () => {
  assert.equal(new Set(ids).size, ids.length);
  assert.ok(ids.every(id => typeof id === 'string' && id.startsWith('ske/')));
});
test('Both portal request journeys and deprecated histories remain available', () => {
  for (const id of ['ske/integrations/portal-controller/backstage/send-resource-requests', 'ske/integrations/portal-controller/cortex/generate-entities', 'ske/integrations/portal-controller/cortex/send-resource-requests', 'ske/integrations/backstage/reference/generator', 'ske/integrations/cortex/installation', 'ske/releases/deprecated/backstage-controller', 'ske/releases/deprecated/backstage-generator', 'ske/releases/deprecated/cortex-controller']) assert.ok(ids.includes(id), id);
});
test('Optional walkthroughs and compatibility pages are outside the sidebar', () => {
  for (const suffix of ['development-image', 'adapter-pipeline-stage', 'delivery-modes', 'request-namespace', 'configuring-oidc', 'air-gapped-plugins', 'entity-yaml-format']) assert.ok(!ids.includes(`ske/integrations/portal-controller/backstage/${suffix}`), suffix);
  assert.ok(!ids.includes('ske/reference/promise-upgrades/intro'));
});
test('Published generated category URLs remain explicit', () => {
  const slugs = groups(sidebars.skeSidebar).map(group => group.link?.slug);
  for (const slug of ['/category/command-reference-1', '/category/platform', '/category/integrations', '/category/pipeline-stages', '/category/deprecated']) assert.ok(slugs.includes(slug), slug);
});
test('Sidebar IDs resolve to built Docusaurus document metadata and existing sources', () => {
  const directory = path.join(__dirname, '../.docusaurus/docusaurus-plugin-content-docs/default');
  const metadata = fs.readdirSync(directory).filter(file => file.startsWith('site-docs-') && file.endsWith('.json')).map(file => JSON.parse(fs.readFileSync(path.join(directory, file), 'utf8')));
  for (const id of ids) {
    const doc = metadata.find(doc => doc.id === id && fs.existsSync(path.join(__dirname, '..', doc.source.replace('@site/', ''))));
    assert.ok(doc, `Missing document metadata for ${id}; run yarn build after adding pages`);
    assert.ok(doc.permalink.startsWith('/ske/'), id);
  }
});

test('Source front matter preserves approved labels in the rendered sidebar', () => {
  const directory = path.join(__dirname, '../.docusaurus/docusaurus-plugin-content-docs/default');
  const metadata = fs.readdirSync(directory).filter(file => file.startsWith('site-docs-') && file.endsWith('.json')).map(file => JSON.parse(fs.readFileSync(path.join(directory, file), 'utf8')));
  const documents = items => items.flatMap(item => item.type === 'category' ? documents(item.items) : [item]);
  const mismatches = [];
  for (const item of documents(sidebars.skeSidebar)) {
    const doc = metadata.find(doc => doc.id === item.id && fs.existsSync(path.join(__dirname, '..', doc.source.replace('@site/', ''))));
    assert.ok(doc, item.id);
    const source = fs.readFileSync(path.join(__dirname, '..', doc.source.replace('@site/', '')), 'utf8');
    const frontMatter = source.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    // Canonical sidebar labels use plain or quoted YAML scalars.
    const match = frontMatter?.[1].match(/^sidebar_label:\s*(.+)$/m);
    const label = match ? match[1].trim().replace(/^(["'])(.*)\1$/, '$2') : item.label;
    if (label !== item.label) mismatches.push(`${item.id}: ${label} → ${item.label}`);
  }
  assert.deepEqual(mismatches, []);
});

test('Built Docusaurus metadata renders approved sidebar and pagination labels', () => {
  const directory = path.join(__dirname, '../.docusaurus/docusaurus-plugin-content-docs/default');
  const metadata = fs.readdirSync(directory).filter(file => file.startsWith('site-docs-') && file.endsWith('.json')).map(file => JSON.parse(fs.readFileSync(path.join(directory, file), 'utf8'))).filter(doc => fs.existsSync(path.join(__dirname, '..', doc.source.replace('@site/', ''))));
  const documents = items => items.flatMap(item => item.type === 'category' ? documents(item.items) : [item]);
  const approved = documents(sidebars.skeSidebar);
  const labelsByPermalink = new Map(approved.map(item => {
    const doc = metadata.find(doc => doc.id === item.id);
    assert.ok(doc, item.id);
    return [doc.permalink, item.label];
  }));
  const mismatches = [];
  for (const item of approved) {
    const doc = metadata.find(doc => doc.id === item.id);
    const label = doc.frontMatter.sidebar_label ?? item.label;
    if (label !== item.label) mismatches.push(`${item.id}: ${label} → ${item.label}`);
    for (const link of [doc.previous, doc.next]) {
      const expectedLabel = labelsByPermalink.get(link?.permalink);
      if (expectedLabel && link.title !== expectedLabel) mismatches.push(`${item.id}: pagination to ${link.permalink} uses ${link.title} → ${expectedLabel}`);
    }
  }
  assert.deepEqual(mismatches, [], 'Run yarn build to regenerate labels after front matter changes');
});
