#!/usr/bin/env sh

set -eux

cat /kratix/input/object.yaml

resourceName=$(yq '.metadata.name' /kratix/input/object.yaml)
namespace="$(yq '.metadata.namespace // "default"' /kratix/input/object.yaml)"
promiseName="redis"

cat <<EOF > /kratix/output/health-definition.yaml
apiVersion: platform.kratix.io/v1alpha1
kind: HealthDefinition
metadata:
  name: ${promiseName}-${resourceName}-${namespace}
  namespace: default
spec:
  resourceRef:
    name: ${resourceName}
    namespace: ${namespace}
  promiseRef:
    name: ${promiseName}
  # runs every minute
  schedule: "* * * * *"
  input: |
    name: ${resourceName}
  workflow:
    apiVersion: platform.kratix.io/v1alpha1
    kind: Pipeline
    metadata:
      name: healthcheck
    spec:
      containers:
      - image: busybox
        name: check-redis
EOF