#!/usr/bin/env sh

namespace="$(yq '.metadata.namespace // "default"' /kratix/input/object.yaml)"
resourceName="$(yq '.metadata.name' /kratix/input/object.yaml)"

while true; do
  state="$(kubectl get redis ${resourceName} --namespace ${namespace} -o jsonpath='{status.healthStatus.healthRecords[0].state}')"
  if [[ "${state}" == "healthy" ]]; then
    break
  fi
  echo "Waiting for resource to be healthy, current state: ${state:-"unknown"}"
  sleep 5
done

echo "Resource is healthy"