name: Build and Push Assets

on:
  push:
    branches: [main]
    paths:
    - assets/*
    - scripts/build-and-push-assets
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push assets
        run: |
          echo "${GITHUB_TOKEN}" | docker login --username syntassodev --password-stdin ghcr.io
          ./scripts/build-and-push-assets
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_PUSH_TOKEN }}